os: linux
dist: bionic

jobs:
  include:
    - stage: docker
      language: generic
      services:
        - docker
      before_install:
        - docker build -t lime docker
    - stage: compile
      language: cpp
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libgsl-dev
      before_install:
        - echo "deb http://nl.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee -a  /etc/apt/sources.list
        - sudo add-apt-repository -y ppa:mhier/libboost-latest
        - sudo apt-get update
        - sudo apt-get install -y libboost1.73-dev libtbb-dev
        - docker build -t lime docker
      env:
        - CC=/usr/bin/gcc-9
        - CXX=/usr/bin/g++-9
      script:
        # Check versions of gcc, g++ and cmake
        - gcc -v && g++ -v && cmake --version

        - mkdir build && cd build
        - cmake ..
        - make lime
