dist: bionic

language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - libtbb-dev
      - libgsl-dev

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get update
  - sudo apt-get install -y libboost1.73-dev

script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

  - mkdir build && cd build
  - cmake ..
  - make lime
